services:
  app:
    container_name: churchdatabase
    image: churchdatabase:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    ports:
      - '8080:8080'

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
